# Generated by Django 3.1.5 on 2021-03-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='belongsTo',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='condor',
            old_name='belongsTo',
            new_name='organisation',
        ),
    ]
