name: CI To Registry

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag django_crm:$(date +%s)
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/django_crm:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Deploy to Minikube
      uses: appleboy/kubectl-action@master
      with:
        config: ${{ env.KUBECONFIG }}
        command: apply
        manifest: |
          apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: django_crm
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: django_crm
              template:
                metadata:
                  labels:
                    app: django_crm
                spec:
                  containers:
                    - name: django_crm
                      image: inveigle/django_crm
                      ports:
                        - containerPort: 80
                      env:
                        - name: ""
                          value: ""
